name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          version: '2024-02-02'

      - name: Run Yosys
        run: |
          mkdir build
          yosys -s synth/tt.ys

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@tt06
